# tools/new-project.sh's template: a project generated from it passes its own gate.
#
#   cmake -DPOLICY_ROOT=<dir> -DWORK=<dir> -DPRESET=<check|win-check> -P run.cmake
#
# The project is generated by new_project.cmake (the script behind new-project.sh), pinned to
# this checkout's commit, and configured with FetchContent pointed at this checkout, so it
# tests the template as it is now, before any release. It must configure, build with
# clang-tidy, pass the audit (policy files unchanged, CI pin, layers) and the format check,
# pass its tests, print its greeting, and make its first commit through its own hooks. Its
# tests must reach CTest one per test case, named and labelled by cpp_policy_add_tests(), and a
# skipped test case must fail the build (POLICY.md 13). It needs VCPKG_ROOT, for doctest. The
# template's lowlevel test prints a std::string_view without including <ostream>, which only
# compiles with Microsoft's library because cpp_policy_add_tests() makes doctest include it.
# Two memory tests and a nanobench speed test (test_benchmark.cpp, with nanobench added to
# vcpkg.json) are added to the project: they must be built in the check build and run only in
# the release build, which must also pass the program's size budget (POLICY.md 13.5, 14.2).

cmake_minimum_required(VERSION 3.29)
find_package(Git REQUIRED)

# Git exports GIT_DIR to hooks (see hooks/run.cmake): keep git on the right repositories.
foreach(variable IN ITEMS GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY)
    unset(ENV{${variable}})
endforeach()
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")

execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${POLICY_ROOT}" rev-parse HEAD
    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)

function(step dir what)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${dir}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "new_project: ${what} failed (exit code ${code})\n${out}${err}")
    endif()
    set(out "${out}${err}" PARENT_SCOPE)
endfunction()

function(generate_and_check)
    set(dest "${WORK}/MyTool")
    step("${WORK}" "generating the project"
        "${CMAKE_COMMAND}" "-DPOLICY_ROOT=${POLICY_ROOT}" "-DDEST=${dest}" -DNAME=MyTool
        "-DCOMMIT=${commit}" -DTAG=v0.0.0 "-DREPOSITORY=https://github.com/luiserh1/cpp-policy.git"
        ${ARGN} -P "${POLICY_ROOT}/cmake/scripts/new_project.cmake")
    step("${dest}" "git init" "${GIT_EXECUTABLE}" init --quiet)
    step("${dest}" "enabling the hooks" "${GIT_EXECUTABLE}" config core.hooksPath tools/hooks)
    file(COPY_FILE "${CMAKE_CURRENT_LIST_DIR}/test_benchmark.cpp" "${dest}/tests/test_benchmark.cpp")
    file(READ "${dest}/vcpkg.json" manifest)
    string(REPLACE "\"dependencies\": [" "\"dependencies\": [\n    {\"name\": \"nanobench\", \"default-features\": false, \"$reason\": \"speed benchmarks\"}," manifest "${manifest}")
    file(WRITE "${dest}/vcpkg.json" "${manifest}")
    file(APPEND "${dest}/tests/CMakeLists.txt"
        "cpp_policy_add_tests(benchmark app SOURCES test_benchmark.cpp LIBRARIES my_tool_core)\n")

    step("${dest}" "configuring the project"
        "${CMAKE_COMMAND}" --preset ${PRESET} "-DFETCHCONTENT_SOURCE_DIR_CPP_POLICY=${POLICY_ROOT}")
    step("${dest}" "building the project (clang-tidy, audit, format check)"
        "${CMAKE_COMMAND}" --build --preset ${PRESET})
    step("${dest}" "testing the project" "${CMAKE_CTEST_COMMAND}" --preset ${PRESET})

    file(GLOB_RECURSE program "${dest}/build/${PRESET}/my_tool" "${dest}/build/${PRESET}/my_tool.exe")
    if(NOT program)
        message(FATAL_ERROR "new_project: the project built no my_tool program")
    endif()
    list(GET program 0 program)
    step("${dest}" "running my_tool" "${CMAKE_COMMAND}" -E env GREETING_NAME=Ada "${program}")
    string(FIND "${out}" "Hello, Ada!" greeted)
    if(greeted EQUAL -1)
        message(FATAL_ERROR "new_project: my_tool didn't greet Ada:\n${out}")
    endif()
endfunction()

# The first commit, through the project's own hooks: pre-commit's audit, format check and
# clang-tidy on every staged file, and commit-msg.
function(first_commit)
    set(dest "${WORK}/MyTool")
    step("${dest}" "staging the project" "${GIT_EXECUTABLE}" add --all)
    file(WRITE "${WORK}/message.txt"
        "chore: create the project\n\nGenerated by cpp-policy's new-project.sh, to start from a project\n"
        "that already passes the gate.\n")
    step("${dest}" "the first commit through the hooks" "${GIT_EXECUTABLE}" -c user.name=test
        -c user.email=test@example.com commit --quiet -F "${WORK}/message.txt")
    string(FIND "${out}" "tidy-files: OK" tidied)
    if(tidied EQUAL -1)
        message(FATAL_ERROR "new_project: pre-commit didn't run tidy-files:\n${out}")
    endif()
endfunction()

# The tests, as CTest sees them: one per test case, with the kind as name prefix and label.
function(check_tests)
    set(dest "${WORK}/MyTool")
    step("${dest}" "listing the unit tests" "${CMAKE_CTEST_COMMAND}" --preset ${PRESET} -N -L "^unit$")
    foreach(test IN ITEMS "unit/app/a name is greeted" "unit/app/empty and too long names are refused"
                          "unit/lowlevel/a variable that isn't set is nothing")
        string(FIND "${out}" "${test}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "new_project: CTest has no unit test '${test}':\n${out}")
        endif()
    endforeach()
    if(NOT out MATCHES "Total Tests: 5\n")
        message(FATAL_ERROR "new_project: expected 5 unit tests, one per test case:\n${out}")
    endif()
    # Benchmarks don't run with sanitizers.
    step("${dest}" "listing the benchmarks" "${CMAKE_CTEST_COMMAND}" --preset ${PRESET} -N -L benchmark)
    if(NOT out MATCHES "Total Tests: 0\n")
        message(FATAL_ERROR "new_project: benchmarks are registered in the ${PRESET} build:\n${out}")
    endif()
endfunction()

# The release workflow: the memory test and the size budget run, and pass.
function(check_release)
    set(dest "${WORK}/MyTool")
    string(REPLACE "check" "release" release "${PRESET}")
    step("${dest}" "configuring ${release}" "${CMAKE_COMMAND}" --preset ${release}
        "-DFETCHCONTENT_SOURCE_DIR_CPP_POLICY=${POLICY_ROOT}")
    step("${dest}" "building ${release}" "${CMAKE_COMMAND}" --build --preset ${release})
    step("${dest}" "testing ${release}" "${CMAKE_CTEST_COMMAND}" --preset ${release})
    foreach(test IN ITEMS "benchmark/app/memory stays flat as the number of greetings grows"
                          "benchmark/app/the heap stays flat as the number of greetings grows"
                          "benchmark/app/greeting speed" "benchmark/size/my_tool")
        string(FIND "${out}" "${test} " found)
        if(found EQUAL -1)
            message(FATAL_ERROR "new_project: ${release} didn't run '${test}':\n${out}")
        endif()
    endforeach()
endfunction()

# A skipped test case fails the build that registers the tests.
function(check_skipped_test_fails)
    set(dest "${WORK}/MyTool")
    file(APPEND "${dest}/tests/test_app.cpp"
        "\nTEST_CASE(\"left for later\" * doctest::skip()) {\n    CHECK(false);\n}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" --build --preset ${PRESET} WORKING_DIRECTORY "${dest}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(code EQUAL 0 OR NOT "${out}${err}" MATCHES "test case \"left for later\" is skipped")
        message(FATAL_ERROR "new_project: a skipped test case didn't fail the build "
            "(exit code ${code}):\n${out}${err}")
    endif()
endfunction()

execute_process(COMMAND "${GIT_EXECUTABLE}" -C "$ENV{VCPKG_ROOT}" rev-parse HEAD
    OUTPUT_VARIABLE baseline OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
generate_and_check("-DVCPKG_BASELINE=${baseline}")
check_tests()
first_commit()
check_release()
check_skipped_test_fails()
message("new_project: OK")
