# tools/new-project.sh's template: a project generated from it passes its own gate.
#
#   cmake -DPOLICY_ROOT=<dir> -DWORK=<dir> -DPRESET=<check|win-check> -P run.cmake
#
# The project is generated by new_project.cmake (the script behind new-project.sh), pinned to
# this checkout's commit, and configured with FetchContent pointed at this checkout, so it
# tests the template as it is now, before any release. It must configure, build with
# clang-tidy, pass the audit (policy files unchanged, CI pin, layers) and the format check,
# pass its tests, print its greeting, and make its first commit through its own hooks. With
# VCPKG_ROOT set, the --vcpkg variant is built and tested too.

cmake_minimum_required(VERSION 3.29)
find_package(Git REQUIRED)

# Git exports GIT_DIR to hooks (see hooks/run.cmake): keep git on the right repositories.
foreach(variable IN ITEMS GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY)
    unset(ENV{${variable}})
endforeach()
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")

execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${POLICY_ROOT}" rev-parse HEAD
    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)

function(step dir what)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${dir}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "new_project: ${what} failed (exit code ${code})\n${out}${err}")
    endif()
    set(out "${out}${err}" PARENT_SCOPE)
endfunction()

function(generate_and_check variant)
    set(dest "${WORK}/${variant}/MyTool")
    step("${WORK}" "generating the ${variant} project"
        "${CMAKE_COMMAND}" "-DPOLICY_ROOT=${POLICY_ROOT}" "-DDEST=${dest}" -DNAME=MyTool
        "-DCOMMIT=${commit}" -DTAG=v0.0.0 "-DREPOSITORY=https://github.com/luiserh1/cpp-policy.git"
        ${ARGN} -P "${POLICY_ROOT}/cmake/scripts/new_project.cmake")
    step("${dest}" "git init" "${GIT_EXECUTABLE}" init --quiet)
    step("${dest}" "enabling the hooks" "${GIT_EXECUTABLE}" config core.hooksPath tools/hooks)

    step("${dest}" "configuring the ${variant} project"
        "${CMAKE_COMMAND}" --preset ${PRESET} "-DFETCHCONTENT_SOURCE_DIR_CPP_POLICY=${POLICY_ROOT}")
    step("${dest}" "building the ${variant} project (clang-tidy, audit, format check)"
        "${CMAKE_COMMAND}" --build --preset ${PRESET})
    step("${dest}" "testing the ${variant} project" "${CMAKE_CTEST_COMMAND}" --preset ${PRESET})

    file(GLOB_RECURSE program "${dest}/build/${PRESET}/my_tool" "${dest}/build/${PRESET}/my_tool.exe")
    if(NOT program)
        message(FATAL_ERROR "new_project: the ${variant} project built no my_tool program")
    endif()
    list(GET program 0 program)
    step("${dest}" "running my_tool" "${CMAKE_COMMAND}" -E env GREETING_NAME=Ada "${program}")
    string(FIND "${out}" "Hello, Ada!" greeted)
    if(greeted EQUAL -1)
        message(FATAL_ERROR "new_project: my_tool didn't greet Ada:\n${out}")
    endif()
endfunction()

# The first commit, through the project's own hooks: pre-commit's audit, format check and
# clang-tidy on every staged file, and commit-msg.
function(first_commit variant)
    set(dest "${WORK}/${variant}/MyTool")
    step("${dest}" "staging the ${variant} project" "${GIT_EXECUTABLE}" add --all)
    file(WRITE "${WORK}/message.txt"
        "chore: create the project\n\nGenerated by cpp-policy's new-project.sh, to start from a project\n"
        "that already passes the gate.\n")
    step("${dest}" "the first commit through the hooks" "${GIT_EXECUTABLE}" -c user.name=test
        -c user.email=test@example.com commit --quiet -F "${WORK}/message.txt")
    string(FIND "${out}" "tidy-files: OK" tidied)
    if(tidied EQUAL -1)
        message(FATAL_ERROR "new_project: pre-commit didn't run tidy-files:\n${out}")
    endif()
endfunction()

generate_and_check(plain)
first_commit(plain)
if(DEFINED ENV{VCPKG_ROOT})
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "$ENV{VCPKG_ROOT}" rev-parse HEAD
        OUTPUT_VARIABLE baseline OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    generate_and_check(vcpkg "-DVCPKG_BASELINE=${baseline}")
else()
    message("new_project: VCPKG_ROOT isn't set; the --vcpkg variant isn't tested")
endif()
message("new_project: OK")
